import generateSlug from '../helpers/generateSlug.js'

let data = [
  {
    firstName: 'Bancroft',
    lastName: 'Shipp',
    email: 'bshipp0@marketwatch.com',
    gender: false,
    birthday: '2005-05-14',
  },
  {
    firstName: 'Sergent',
    lastName: 'MacSorley',
    email: 'smacsorley1@indiegogo.com',
    gender: false,
    birthday: '2019-08-24',
  },
  {
    firstName: 'Hagen',
    lastName: 'Adami',
    email: 'hadami2@noaa.gov',
    gender: false,
    birthday: '2014-04-15',
  },
  {
    firstName: 'Gus',
    lastName: 'Pople',
    email: 'gpople3@independent.co.uk',
    gender: false,
    birthday: '2008-03-26',
  },
  {
    firstName: 'Hetti',
    lastName: 'Stubbin',
    email: 'hstubbin4@moonfruit.com',
    gender: true,
    birthday: '2013-06-16',
  },
  {
    firstName: 'Barbe',
    lastName: 'Gherardesci',
    email: 'bgherardesci5@barnesandnoble.com',
    gender: true,
    birthday: '2016-03-15',
  },
  {
    firstName: 'Beau',
    lastName: 'Sweating',
    email: 'bsweating6@diigo.com',
    gender: false,
    birthday: '2003-06-25',
  },
  {
    firstName: 'Arnold',
    lastName: 'Algar',
    email: 'aalgar7@virginia.edu',
    gender: false,
    birthday: '2001-04-21',
  },
  {
    firstName: 'Bartholemy',
    lastName: 'Ibbetson',
    email: 'bibbetson8@meetup.com',
    gender: false,
    birthday: '2018-03-11',
  },
  {
    firstName: 'Brana',
    lastName: 'Cady',
    email: 'bcady9@google.com.au',
    gender: true,
    birthday: '2022-01-11',
  },
  {
    firstName: 'Orelie',
    lastName: 'Bellefonte',
    email: 'obellefontea@go.com',
    gender: true,
    birthday: '2003-03-18',
  },
  {
    firstName: 'Mallissa',
    lastName: 'Lammerts',
    email: 'mlammertsb@sitemeter.com',
    gender: true,
    birthday: '2005-09-01',
  },
  {
    firstName: 'Juana',
    lastName: 'Blackledge',
    email: 'jblackledgec@sourceforge.net',
    gender: true,
    birthday: '2009-04-26',
  },
  {
    firstName: 'Franz',
    lastName: 'Lanphier',
    email: 'flanphierd@ft.com',
    gender: false,
    birthday: '2016-05-02',
  },
  {
    firstName: 'Lotte',
    lastName: 'Wolfers',
    email: 'lwolferse@nps.gov',
    gender: true,
    birthday: '2001-09-08',
  },
  {
    firstName: 'Christa',
    lastName: 'McCorry',
    email: 'cmccorryf@mozilla.org',
    gender: true,
    birthday: '2012-10-08',
  },
  {
    firstName: 'Beverlee',
    lastName: 'Odo',
    email: 'bodog@craigslist.org',
    gender: true,
    birthday: '2011-07-10',
  },
  {
    firstName: 'Joellen',
    lastName: 'Munkley',
    email: 'jmunkleyh@princeton.edu',
    gender: true,
    birthday: '2008-08-24',
  },
  {
    firstName: 'Zachary',
    lastName: 'Coggeshall',
    email: 'zcoggeshalli@ucla.edu',
    gender: false,
    birthday: '2021-12-16',
  },
  {
    firstName: 'Rafaela',
    lastName: 'Palia',
    email: 'rpaliaj@homestead.com',
    gender: false,
    birthday: '2015-03-03',
  },
  {
    firstName: 'Karole',
    lastName: 'Bengal',
    email: 'kbengalk@un.org',
    gender: true,
    birthday: '2017-08-10',
  },
  {
    firstName: 'Gregg',
    lastName: 'Scotchmer',
    email: 'gscotchmerl@xing.com',
    gender: false,
    birthday: '2006-05-10',
  },
  {
    firstName: 'Ardene',
    lastName: 'Antonetti',
    email: 'aantonettim@narod.ru',
    gender: true,
    birthday: '2019-12-22',
  },
  {
    firstName: 'Kiley',
    lastName: 'Dungee',
    email: 'kdungeen@friendfeed.com',
    gender: false,
    birthday: '2014-12-17',
  },
  {
    firstName: 'Ursa',
    lastName: 'Cowdray',
    email: 'ucowdrayo@dagondesign.com',
    gender: true,
    birthday: '2011-12-25',
  },
  {
    firstName: 'Dav',
    lastName: 'Sentance',
    email: 'dsentancep@miitbeian.gov.cn',
    gender: false,
    birthday: '2022-06-28',
  },
  {
    firstName: 'Dilan',
    lastName: 'Kay',
    email: 'dkayq@mapquest.com',
    gender: false,
    birthday: '2002-04-28',
  },
  {
    firstName: 'Karilynn',
    lastName: 'Steptoe',
    email: 'ksteptoer@umich.edu',
    gender: true,
    birthday: '2012-02-14',
  },
  {
    firstName: 'Blake',
    lastName: 'Sysland',
    email: 'bsyslands@chicagotribune.com',
    gender: true,
    birthday: '2015-10-13',
  },
  {
    firstName: 'Dalton',
    lastName: 'Mottinelli',
    email: 'dmottinellit@skyrock.com',
    gender: false,
    birthday: '2002-02-21',
  },
  {
    firstName: 'Gare',
    lastName: 'Woolager',
    email: 'gwoolageru@webmd.com',
    gender: false,
    birthday: '2019-09-20',
  },
  {
    firstName: 'Wilow',
    lastName: 'Meininger',
    email: 'wmeiningerv@comsenz.com',
    gender: true,
    birthday: '2017-01-29',
  },
  {
    firstName: 'Hammad',
    lastName: 'Dregan',
    email: 'hdreganw@amazon.co.jp',
    gender: false,
    birthday: '2014-10-15',
  },
  {
    firstName: 'Kiley',
    lastName: 'Melloy',
    email: 'kmelloyx@craigslist.org',
    gender: false,
    birthday: '2014-09-19',
  },
  {
    firstName: 'Jamison',
    lastName: 'Derges',
    email: 'jdergesy@ow.ly',
    gender: false,
    birthday: '2004-01-01',
  },
  {
    firstName: 'Joceline',
    lastName: 'Canas',
    email: 'jcanasz@bbb.org',
    gender: true,
    birthday: '2006-08-10',
  },
  {
    firstName: 'Darb',
    lastName: 'Lannen',
    email: 'dlannen10@eventbrite.com',
    gender: true,
    birthday: '2021-03-22',
  },
  {
    firstName: 'Rollie',
    lastName: 'Poppleston',
    email: 'rpoppleston11@dailymotion.com',
    gender: false,
    birthday: '2007-06-22',
  },
  {
    firstName: 'Augustine',
    lastName: 'Snelling',
    email: 'asnelling12@hibu.com',
    gender: false,
    birthday: '2011-06-29',
  },
  {
    firstName: 'Peta',
    lastName: 'Barrat',
    email: 'pbarrat13@furl.net',
    gender: false,
    birthday: '2009-02-04',
  },
  {
    firstName: 'Shaine',
    lastName: 'Baggally',
    email: 'sbaggally14@mysql.com',
    gender: false,
    birthday: '2002-07-13',
  },
  {
    firstName: 'Lauri',
    lastName: 'Genike',
    email: 'lgenike15@hc360.com',
    gender: true,
    birthday: '2016-09-26',
  },
  {
    firstName: 'Deeann',
    lastName: 'Sidworth',
    email: 'dsidworth16@msn.com',
    gender: true,
    birthday: '2008-09-26',
  },
  {
    firstName: 'Kelley',
    lastName: 'Clarabut',
    email: 'kclarabut17@sphinn.com',
    gender: false,
    birthday: '2017-01-25',
  },
  {
    firstName: 'Robby',
    lastName: 'Dawks',
    email: 'rdawks18@arizona.edu',
    gender: true,
    birthday: '2019-12-31',
  },
  {
    firstName: 'Adela',
    lastName: 'Odegaard',
    email: 'aodegaard19@theguardian.com',
    gender: true,
    birthday: '2009-12-09',
  },
  {
    firstName: 'Maudie',
    lastName: 'Twamley',
    email: 'mtwamley1a@jugem.jp',
    gender: true,
    birthday: '2008-06-08',
  },
  {
    firstName: 'Marielle',
    lastName: 'Pickett',
    email: 'mpickett1b@un.org',
    gender: true,
    birthday: '2003-09-04',
  },
  {
    firstName: 'Nancee',
    lastName: 'Sambiedge',
    email: 'nsambiedge1c@apple.com',
    gender: true,
    birthday: '2010-07-03',
  },
  {
    firstName: 'Vasili',
    lastName: 'Creeboe',
    email: 'vcreeboe1d@wisc.edu',
    gender: false,
    birthday: '2004-10-31',
  },
  {
    firstName: 'Lily',
    lastName: 'Ricardou',
    email: 'lricardou1e@live.com',
    gender: true,
    birthday: '2021-04-26',
  },
  {
    firstName: 'Arni',
    lastName: 'Sawl',
    email: 'asawl1f@artisteer.com',
    gender: false,
    birthday: '2018-10-10',
  },
  {
    firstName: 'Odelia',
    lastName: 'Eldridge',
    email: 'oeldridge1g@addthis.com',
    gender: true,
    birthday: '2005-01-18',
  },
  {
    firstName: 'Alika',
    lastName: 'Rasp',
    email: 'arasp1h@about.com',
    gender: true,
    birthday: '2002-12-18',
  },
  {
    firstName: 'Raphaela',
    lastName: 'Debenham',
    email: 'rdebenham1i@google.de',
    gender: true,
    birthday: '2003-09-17',
  },
  {
    firstName: 'Francesco',
    lastName: 'Castanos',
    email: 'fcastanos1j@webmd.com',
    gender: false,
    birthday: '2005-01-07',
  },
  {
    firstName: 'Lock',
    lastName: 'Lowings',
    email: 'llowings1k@elpais.com',
    gender: false,
    birthday: '2019-10-15',
  },
  {
    firstName: 'Stillman',
    lastName: 'Searl',
    email: 'ssearl1l@meetup.com',
    gender: false,
    birthday: '2012-11-29',
  },
  {
    firstName: 'Jo',
    lastName: 'Hechlin',
    email: 'jhechlin1m@gravatar.com',
    gender: false,
    birthday: '2003-10-10',
  },
  {
    firstName: 'Raymond',
    lastName: 'Goodrum',
    email: 'rgoodrum1n@multiply.com',
    gender: false,
    birthday: '2010-08-25',
  },
  {
    firstName: 'Woody',
    lastName: 'Perview',
    email: 'wperview1o@taobao.com',
    gender: false,
    birthday: '2011-01-15',
  },
  {
    firstName: 'Thadeus',
    lastName: 'Hobbert',
    email: 'thobbert1p@harvard.edu',
    gender: false,
    birthday: '2012-08-28',
  },
  {
    firstName: 'Julina',
    lastName: 'McCue',
    email: 'jmccue1q@miibeian.gov.cn',
    gender: true,
    birthday: '2011-02-04',
  },
  {
    firstName: 'Lusa',
    lastName: 'Liver',
    email: 'lliver1r@ft.com',
    gender: true,
    birthday: '2021-10-07',
  },
  {
    firstName: 'Poul',
    lastName: 'Clough',
    email: 'pclough1s@godaddy.com',
    gender: false,
    birthday: '2014-08-08',
  },
  {
    firstName: 'Herbert',
    lastName: 'Duesbury',
    email: 'hduesbury1t@mapy.cz',
    gender: false,
    birthday: '2000-09-24',
  },
  {
    firstName: 'Thoma',
    lastName: 'De-Ville',
    email: 'tdeville1u@vistaprint.com',
    gender: false,
    birthday: '2005-11-18',
  },
  {
    firstName: 'Tracy',
    lastName: 'Elcoat',
    email: 'telcoat1v@artisteer.com',
    gender: false,
    birthday: '2021-02-21',
  },
  {
    firstName: 'Haslett',
    lastName: "O'Brian",
    email: 'hobrian1w@comsenz.com',
    gender: false,
    birthday: '2020-02-03',
  },
  {
    firstName: 'Cyndie',
    lastName: 'Scapelhorn',
    email: 'cscapelhorn1x@list-manage.com',
    gender: true,
    birthday: '2006-02-27',
  },
  {
    firstName: 'Adorne',
    lastName: 'Gaukroger',
    email: 'agaukroger1y@prweb.com',
    gender: true,
    birthday: '2011-12-13',
  },
  {
    firstName: 'Lyssa',
    lastName: 'Sisselot',
    email: 'lsisselot1z@paypal.com',
    gender: true,
    birthday: '2017-07-06',
  },
  {
    firstName: 'Laurence',
    lastName: 'Thompson',
    email: 'lthompson20@usda.gov',
    gender: false,
    birthday: '2018-10-29',
  },
  {
    firstName: 'Cesaro',
    lastName: 'Bravery',
    email: 'cbravery21@usatoday.com',
    gender: false,
    birthday: '2006-07-26',
  },
  {
    firstName: 'Stearne',
    lastName: 'Toffel',
    email: 'stoffel22@umich.edu',
    gender: false,
    birthday: '2000-09-12',
  },
  {
    firstName: 'Claiborn',
    lastName: 'Downgate',
    email: 'cdowngate23@mit.edu',
    gender: false,
    birthday: '2014-05-17',
  },
  {
    firstName: 'Malcolm',
    lastName: 'Berni',
    email: 'mberni24@theatlantic.com',
    gender: false,
    birthday: '2018-01-16',
  },
  {
    firstName: 'Anna-diana',
    lastName: 'Dursley',
    email: 'adursley25@deviantart.com',
    gender: false,
    birthday: '2007-03-27',
  },
  {
    firstName: 'Wynn',
    lastName: 'Winslett',
    email: 'wwinslett26@trellian.com',
    gender: false,
    birthday: '2006-06-27',
  },
  {
    firstName: 'Elset',
    lastName: 'Craydon',
    email: 'ecraydon27@illinois.edu',
    gender: true,
    birthday: '2002-05-19',
  },
  {
    firstName: 'Nevin',
    lastName: 'Deave',
    email: 'ndeave28@opensource.org',
    gender: false,
    birthday: '2021-10-27',
  },
  {
    firstName: 'Bret',
    lastName: 'Arthur',
    email: 'barthur29@edublogs.org',
    gender: false,
    birthday: '2001-04-14',
  },
  {
    firstName: 'Valentine',
    lastName: 'Sphinxe',
    email: 'vsphinxe2a@cloudflare.com',
    gender: false,
    birthday: '2017-06-07',
  },
  {
    firstName: 'Laetitia',
    lastName: 'Meadus',
    email: 'lmeadus2b@posterous.com',
    gender: true,
    birthday: '2003-11-21',
  },
  {
    firstName: 'Griffie',
    lastName: 'Gransden',
    email: 'ggransden2c@gizmodo.com',
    gender: false,
    birthday: '2001-07-09',
  },
  {
    firstName: 'Yehudi',
    lastName: 'Gostage',
    email: 'ygostage2d@indiegogo.com',
    gender: false,
    birthday: '2002-10-12',
  },
  {
    firstName: 'Alvinia',
    lastName: 'Wickstead',
    email: 'awickstead2e@webnode.com',
    gender: true,
    birthday: '2012-11-23',
  },
  {
    firstName: 'Bernarr',
    lastName: 'Kief',
    email: 'bkief2f@creativecommons.org',
    gender: false,
    birthday: '2003-09-15',
  },
  {
    firstName: 'Zak',
    lastName: 'Manifould',
    email: 'zmanifould2g@constantcontact.com',
    gender: false,
    birthday: '2002-05-16',
  },
  {
    firstName: 'Glenda',
    lastName: 'Claricoates',
    email: 'gclaricoates2h@umich.edu',
    gender: true,
    birthday: '2006-02-26',
  },
  {
    firstName: 'Jacques',
    lastName: 'Clearie',
    email: 'jclearie2i@unblog.fr',
    gender: false,
    birthday: '2005-10-30',
  },
  {
    firstName: 'Buddy',
    lastName: 'Tate',
    email: 'btate2j@chron.com',
    gender: false,
    birthday: '2018-12-05',
  },
  {
    firstName: 'Moria',
    lastName: 'Tumilson',
    email: 'mtumilson2k@edublogs.org',
    gender: true,
    birthday: '2012-01-16',
  },
  {
    firstName: 'Case',
    lastName: 'Gainor',
    email: 'cgainor2l@senate.gov',
    gender: false,
    birthday: '2003-08-19',
  },
  {
    firstName: 'Daffy',
    lastName: 'Wayne',
    email: 'dwayne2m@google.co.jp',
    gender: true,
    birthday: '2003-01-10',
  },
  {
    firstName: 'Haslett',
    lastName: 'Bagley',
    email: 'hbagley2n@who.int',
    gender: false,
    birthday: '2001-10-05',
  },
  {
    firstName: 'Bertrand',
    lastName: 'Cordsen',
    email: 'bcordsen2o@hexun.com',
    gender: false,
    birthday: '2007-03-04',
  },
  {
    firstName: 'Kasey',
    lastName: 'Retter',
    email: 'kretter2p@sourceforge.net',
    gender: true,
    birthday: '2005-10-29',
  },
  {
    firstName: 'Lennie',
    lastName: 'Seed',
    email: 'lseed2q@cpanel.net',
    gender: false,
    birthday: '2012-12-15',
  },
  {
    firstName: 'Katherine',
    lastName: 'Riccio',
    email: 'kriccio2r@deviantart.com',
    gender: true,
    birthday: '2011-01-14',
  },
]

data = data.map((item) => ({
  ...item,
  username: generateSlug(item.firstName + '-' + item.lastName),
  password: '12345678',
  avatar: 'https://picsum.photos/200/300',
}))

export default data
